export const meta = {
  name: 'new-framework-candidates',
  description: 'Sweep repo + external literature for MOF candidates beyond ZIF-69 for humid 0.15 bar CO2 capture; verify adversarially; judge',
  phases: [
    { title: 'Repo', detail: 'registered criteria, pipeline limits, candidates already set aside' },
    { title: 'External', detail: 'six modalities of web literature sweep' },
    { title: 'Merge', detail: 'dedupe into a candidate roster' },
    { title: 'Verify', detail: 'evidence refuter + pipeline-fit refuter per candidate' },
    { title: 'Judge', detail: 'three judges + completeness critic' },
  ],
}

const REPO = '/home/mangwon1/mof_project'
const CTX = `Project context (read-only facts): The repo at ${REPO} is a MOF simulation project for CO2 capture from wet flue gas (CO2 0.15 bar, 298 K, RH 90 %, TSA 298->373 K). Current line: ZIF-69 (gme) multivariate imidazolate substitution (saIm = sulfonic-acid imidazolate etc.). Pipeline: RASPA rigid-framework GCMC (UFF_MOF, Garcia-Sanchez CO2, TIP5P-Ew water), PACMAN DDEC6 charges, xtb GFN-FF relaxation, Zeo++ gates (PLD/LCD), ensembles of realizations, 1.5-unit rule (differences < 1.5 x 95 % CI are not ranked). Chemisorption (amine carbamate/bicarbonate) and open-metal-site water chemistry cannot be modelled; physisorption only. Key registered findings: within ZIF-69, retention (RH90/RH0) and absolute uptake trade off; nothing beats saIm050 on both axes; batch (arrangement) scatter 8.7 p exceeds candidate differences. The user now asks for COMPLETELY NEW frameworks: any topology, metal, or ligand.`

const CAND_SCHEMA = {
  type: 'object',
  properties: {
    candidates: { type: 'array', items: { type: 'object', properties: {
      name: { type: 'string' }, family: { type: 'string' }, topology: { type: 'string' }, metal: { type: 'string' },
      linkers: { type: 'string' }, pore_metrics: { type: 'string' },
      co2_015bar: { type: 'string' }, humid_evidence: { type: 'string' }, water_isotherm: { type: 'string' },
      synthesis_status: { type: 'string' }, sources: { type: 'array', items: { type: 'string' } },
      pipeline_modelable: { type: 'string' }, mtv_headroom: { type: 'string' }, risks: { type: 'string' },
      evidence_grade: { type: 'string' } }, required: ['name','family','sources','humid_evidence','pipeline_modelable'] } },
    notes: { type: 'string' },
    not_found: { type: 'array', items: { type: 'string' } },
  }, required: ['candidates','notes'] }

const REPO_SCHEMA = { type: 'object', properties: { summary: { type: 'string' }, items: { type: 'array', items: { type: 'object', properties: { topic: { type: 'string' }, fact: { type: 'string' }, file: { type: 'string' } }, required: ['topic','fact','file'] } } }, required: ['summary','items'] }

const OUT = 'Return raw data only via the structured output; no prose for a human. Every numeric claim must carry a source (DOI or URL or repo file path). Mark unverifiable numbers "[미확인]". Do not invent DOIs; if you cannot confirm a DOI, give the URL you actually opened. Use WebSearch/WebFetch; when a publisher blocks you (403), try Semantic Scholar API (api.semanticscholar.org/graph/v1), Crossref, PMC, arXiv/ChemRxiv, or Google Scholar snippets.'

phase('Repo')
const repoTasks = [
  { key: 'criteria', prompt: `${CTX}\nRead in ${REPO}: CLAUDE.md, 21_ZIF69_MTV/DESIGN_STUDY_20260903.md (esp. §0, §1, §5, §6), 21_ZIF69_MTV/RULER_DECISION_20260828.md if present, 21_ZIF69_MTV/TIERS.md, 15_Target/optimal_qst.py and target_analysis.json, HANDOVER.md §1-§5, 21_ZIF69_MTV/NEW_MACHINE_20260822.md §0-1. Extract: (a) every registered performance criterion/threshold a candidate must meet (metrics, pressures, RH, TSA temperatures, Q_st target 30-40 kJ/mol and its derivation, 1.5-unit rule, ensemble rules), (b) every pipeline limitation (rigid GCMC, force fields, what chemistries cannot be modelled, Zeo++ gate thresholds, xtb relax, PACMAN), (c) the chain of decisions that led to ZIF-69 (HANDOVER §3, 20_ParentScan/README.md, 02_HTS_Master_Results/REEVAL_V2_PLAN.md and the CSV headers). Return items with file paths.` },
  { key: 'set-aside', prompt: `${CTX}\nSearch ${REPO} (grep across *.md, esp. 21_ZIF69_MTV/DESIGN_STUDY_20260903.md §3-2, LITERATURE_20260819.md, LITERATURE_NOTES_20260824.md, LITERATURE_COREMOF_20260904.md, LITERATURE_INDEX.md, 20_ParentScan/README.md, 14_Strategies, 11_Novelty/NOVELTY_NOTE.md, 02_HTS_Master_Results/*.csv, 21_ZIF69_MTV/MAGI/*.md, 21_LinkerDesign/DESIGN_BRIEF.md) for EVERY non-ZIF-69 framework or framework family that was ever considered, benchmarked, or named (e.g. ZIF-7, ZIF-8, ZIF-67, ZIF-2, ZIF-77, ZIF-300 series, npo ZIF-1001, Fe2(bdp)3 VICDOC, Mg-MOF-74, MFU-4l, Co-MOF-9/10, CUK-1, Al-PMOF, CALF-20, ZIF-94, UZIF-31~33, ZIF-22, EMM-19, CoRE-MOF top hits...). For each: what was said, the numbers cited, the verdict/reason it was set aside or kept, and the file. Also list every EXTERNAL benchmark material with humid CO2 data that the repo cites (with the cited numbers).` },
  { key: 'endnote', prompt: `${CTX}\nThe EndNote PDF library is NOT on this machine, but 21_ZIF69_MTV/LITERATURE_INDEX.md (69 records with one-line relevance tags), LITERATURE_NOTES_20260824.md (deep-read notes), LITERATURE_COREMOF_20260904.md, and ~/.claude/uploads/*/ (a few PDFs; read them with python pypdf from /home/mangwon1/miniconda3/envs/czeromof/bin/python if available, else pdftotext) are. From these, list every framework/material with humid or water-competition CO2 data or design rules the library holds that point AWAY from ZIF-69/gme: material name, numbers, the paper (author year DOI), and what design rule it supports (e.g. ultramicropore N2 exclusion, 1D channel prevents water clustering, hydrophobic + CO2-philic, sulfone sites, azolate hydrophobicity). Return items with the index id and file.` },
]
const repo = (await parallel(repoTasks.map(t => () => agent(t.prompt + '\n' + OUT, { label: `repo:${t.key}`, phase: 'Repo', schema: REPO_SCHEMA, model: 'opus' })))).filter(Boolean)
const repoDigest = repo.map(r => r.summary + '\n' + r.items.map(i => `- [${i.topic}] ${i.fact} (${i.file})`).join('\n')).join('\n\n')
log(`repo sweep: ${repo.length}/3 agents, ${repo.reduce((n, r) => n + r.items.length, 0)} facts`)

phase('External')
const EXT = [
  { key: 'proven-humid', prompt: `Modality: EXPERIMENTALLY PROVEN humid flue-gas CO2 PHYSISORBENTS. Find every framework with published CO2 uptake at ~0.15 bar/298 K AND a humid measurement (RH >= 30 %, equilibrium co-adsorption or breakthrough), e.g. CALF-20 (Zn triazolate oxalate, Science 2021), SIFSIX-3-Ni, NbOFFIVE-1-Ni, ZnAtzOx / Zn(atz)(ox), UTSA-16, MIL-160, Al-fumarate, CD-MOF-2, ZIF-94/SIM-1, ZIF-300/301/302, Fe2(bdp)3, MOF-303/MIL-53 variants, HKUST-1 (as negative), Mg-MOF-74 (as negative). For each give the actual numbers and whether the humid value is equilibrium or dynamic. Aim for >= 12 candidates.` },
  { key: 'azolate-topologies', prompt: `Modality: NEW ZIF/AZOLATE TOPOLOGIES AND UNUSUAL LINKERS. Enumerate frameworks outside gme ZIF-69: small-pore ZIFs (npo ZIF-1001 Zn3(bTZ)4.5(bIm)1.5, cag ZIF-4/62, crb ZIF-2, frl ZIF-77, RHO ZIF-71/93/94/97, lta ZIF-76, cha ZIF-300s, moz ZIF-100, poz/mzt ZIF-412/413/414, UZIF-31/32/33, ZIF-725, ZIF-8 derivatives with 2-CF3/2-Cl/2-Br/purine/2-aminobenzimidazole/4,5-dichloro/2-carboxaldehyde), triazolate/tetrazolate/pyrazolate MAFs (MAF-4/5/6/7/66, MAF-X series), Zn/Co/Cu azolate-carboxylate hybrids, 2D ZIF-L and Zn2(bim)4 nanosheets. For each: topology, PLD/LCD, CO2 low-pressure uptake, any water/humid data, synthesis status, and what substitution headroom (multivariate mixing) exists. Aim for >= 15.` },
  { key: 'comp-screening', prompt: `Modality: COMPUTATIONAL SCREENING / DESIGN PAPERS for humid CO2 capture (2016-2026): CoRE MOF 2025 (Zhao et al. Matter 8, 102140), Jiang 2023 SusMat "Screening, preparation, and prototyping of MOFs for adsorptive carbon capture under humid conditions", Boyd et al. Nature 2019 adsorbaphore (Al-PMOF/Al-PyrMOF), Li/Chung/Snurr 2016 water K_H, Snurr hMOF humid screens, Sholl/Keskin CO2/N2/H2O membrane and adsorption screens, Smit group wet flue gas ML, Moosavi/Smit "understanding the diversity", Daglar/Keskin 2022-2024 humid screens, and any 2024-2026 screens (ML or GCMC). Extract: which structure families/top materials win under humidity, which descriptors (PLD 3.2-4.0 A N2 exclusion, 1D channels, hydrophobic + CO2-philic sites, low water K_H but high CO2 K_H, sulfone/nitro/aza acceptor sites) and the winners' names with numbers. Aim for >= 10 named winners.` },
  { key: 'mechanism-families', prompt: `Modality: MECHANISM-DRIVEN FAMILIES beyond azolates that keep CO2 uptake under humidity by PHYSISORPTION: fluorinated-anion pillared ultramicroporous (SIFSIX/NbOFFIVE/TIFSIX/ZU-, KAUST-7/8), oxalate/formate frameworks (Zn(ox)(atz), Mg formate, MOF-CD), Al/ Fe carboxylates with hydrophilic-but-CO2-philic channels (MIL-160, CAU-10-H, MIL-53-X, MOF-303), rare-earth fcu (Y/Tb-fum-fcu), ultramicroporous Cu/Ni pyrazolates, sulfone-immobilized Zn-MOF (ACS AMI 2020 10.1021/acsami.0c07380), methylated/fluorinated hydrophobic-pore MOFs (Cu(F-pymo), ZIF-71 style), and 'cooperative water' materials where H2O ENHANCES CO2 (report them but flag if the mechanism is bicarbonate chemisorption = not modelable). For each: metal/linker/topology, pore size, CO2 0.15 bar, humid data, stability to humid cycling, and whether physisorption. Aim for >= 12.` },
  { key: 'synthesis-feasibility', prompt: `Modality: SYNTHESIS FEASIBILITY AND SCALE. For the leading humid-CO2 physisorbent frameworks (CALF-20, SIFSIX-3-Ni, NbOFFIVE-1-Ni, ZnAtzOx, MIL-160, Al-fumarate/Basolite A520, UTSA-16, ZIF-94, ZIF-8 family, MAF-4/6/7, Fe2(bdp)3, CAU-10, MOF-303, ZIF-300s) find: reported synthesis conditions (aqueous? room temperature? solvothermal?), linker commercial availability and rough price class, gram-to-kilogram scale-up reports (e.g. Svante CALF-20, BASF Basolite, Nuada), hydrothermal/cycling stability data, shaping (pellets/monoliths). Also list which unusual azoles are commercially available (e.g. 3-amino-1,2,4-triazole, 1,2,4-triazole, tetrazole, 2-trifluoromethylimidazole, 4,5-dichloroimidazole, purine, imidazole-2-carboxaldehyde, 2-methylbenzimidazole, 5-azabenzimidazole = imidazo[4,5-c]pyridine). Give sources.` },
  { key: 'wild-cards', prompt: `Modality: WILD CARDS - frameworks that break with all of the above but still are MOFs/coordination networks with humid CO2 physisorption promise: 2D layered MOFs and nanosheets, MOF glasses, ionic/anionic frameworks with extra-framework cations (e.g. Cu-BTTri? no, focus physisorption), metal-cyanide/Prussian-blue analogues, hydrogen-bonded metal complexes, coordination polymers with 1D channels (e.g. Zn(pyrazolate)), squarate/oxalate ultramicroporous (Ca/Mg squarate, UTSA-280), phosphonate/ sulfonate frameworks, water-harvesting MOFs repurposed (MOF-303, MOF-801) as 'water-tolerant CO2' hosts, and ionic liquid/salt-impregnated frameworks (flag as not modelable if chemisorptive). For each: why it might beat azolate ZIFs on the humid retention x absolute uptake trade-off, numbers if any, and modelability. Aim for >= 10, and explicitly mark speculative ones.` },
]
const ext = (await parallel(EXT.map(e => () => agent(`${CTX}\nRepo digest (what is already known/considered; do not simply repeat it, but you may correct it):\n${repoDigest.slice(0, 12000)}\n\n${e.prompt}\n\nFor every candidate fill: name, family, topology, metal, linkers (SMILES if known), pore_metrics (PLD/LCD), co2_015bar, humid_evidence (RH, retention or humid uptake, equilibrium vs breakthrough), water_isotherm (yes/no + shape), synthesis_status, sources (DOI/URL), pipeline_modelable (rigid GCMC/UFF_MOF/DDEC6/TIP5P-Ew; OMS or chemisorption = limited), mtv_headroom (what linker mixing / substitution positions exist), risks, evidence_grade ([전문]=read full text, [요지]=abstract, [미확인]=unverified). Also list not_found: things you searched for and could not confirm.\n${OUT}`, { label: `ext:${e.key}`, phase: 'External', schema: CAND_SCHEMA, model: 'opus' })))).filter(Boolean)
const rawCands = ext.flatMap(r => r.candidates)
log(`external sweep: ${ext.length}/6 modalities, ${rawCands.length} raw candidates`)

phase('Merge')
const ROSTER_SCHEMA = { type: 'object', properties: { roster: { type: 'array', items: { type: 'object', properties: { name: { type: 'string' }, family: { type: 'string' }, merged_from: { type: 'array', items: { type: 'string' } }, one_line: { type: 'string' }, key_numbers: { type: 'string' }, sources: { type: 'array', items: { type: 'string' } }, pipeline_modelable: { type: 'string' }, mtv_headroom: { type: 'string' }, risks: { type: 'string' } }, required: ['name','family','one_line','sources','pipeline_modelable'] } }, dropped: { type: 'array', items: { type: 'string' } } }, required: ['roster','dropped'] }
const merged = await agent(`${CTX}\nHere are ${rawCands.length} raw candidate records from six literature sweeps (JSON):\n${JSON.stringify(rawCands).slice(0, 60000)}\n\nDeduplicate (same framework under different names -> one entry), merge their evidence, and produce a roster of AT MOST 14 distinct frameworks or tightly-defined families that best fit: physisorption, humid retention evidence, absolute CO2 at 0.15 bar, modelable with rigid GCMC, and having multivariate/substitution headroom (the project's method is linker mixing). Prefer diversity across families (azolate, fluorinated-anion, carboxylate, oxalate, wild) over many near-duplicates. Keep chemisorptive materials out of the roster but name them in dropped with the reason. List every dropped item with a reason.\n${OUT}`, { label: 'merge', phase: 'Merge', schema: ROSTER_SCHEMA, model: 'opus' })
const roster = merged ? merged.roster : []
log(`roster: ${roster.length} candidates; dropped ${merged ? merged.dropped.length : 0}`)

phase('Verify')
const VERDICT = { type: 'object', properties: { refuted: { type: 'boolean' }, confidence: { type: 'number' }, reasons: { type: 'string' }, corrected_facts: { type: 'string' }, verified_sources: { type: 'array', items: { type: 'string' } } }, required: ['refuted','confidence','reasons'] }
const verified = await pipeline(roster,
  c => parallel([
    () => agent(`${CTX}\nCandidate: ${JSON.stringify(c)}\nLens: EVIDENCE. Try to REFUTE the factual claims: does the humid CO2 data really exist at the stated RH/pressure, is it equilibrium or breakthrough, are the numbers right, do the cited DOIs resolve to the claimed papers, is the synthesis actually reported? Open the sources (or Semantic Scholar/Crossref metadata) and check. Default refuted=true if you cannot confirm the central humid claim from any source. Report corrected facts.\n${OUT}`, { label: `verify-evidence:${c.name}`, phase: 'Verify', schema: VERDICT, model: 'opus' }),
    () => agent(`${CTX}\nCandidate: ${JSON.stringify(c)}\nLens: PIPELINE FIT & DESIGN HEADROOM. Try to REFUTE that this candidate is worth our compute: (1) can rigid-framework GCMC with UFF_MOF + DDEC6 + TIP5P-Ew model its CO2/H2O physisorption credibly (open metal sites with coordinated water, flexible gating, chemisorption, extra-framework ions, disorder -> refute), (2) is there a CIF (CSD refcode / CoRE MOF entry) we can obtain, (3) does linker mixing / substitution actually have headroom in this framework (or is it already optimal / has no substituent positions), (4) does the 0.15 bar / RH90 / TSA 298->373 K metric make sense for it (e.g. materials that need VSA or that lose CO2 to water at RH90). Default refuted=true if two or more of (1)-(4) fail. Report corrected facts and, if it survives, the CSD refcode and the concrete substitution positions.\n${OUT}`, { label: `verify-fit:${c.name}`, phase: 'Verify', schema: VERDICT, model: 'opus' }),
  ]).then(v => ({ c, evidence: v[0], fit: v[1] }))
)
const survivors = verified.filter(Boolean).filter(v => v.evidence && v.fit && !v.evidence.refuted && !v.fit.refuted)
const killed = verified.filter(Boolean).filter(v => !(v.evidence && v.fit && !v.evidence.refuted && !v.fit.refuted))
log(`verify: ${survivors.length} survive, ${killed.length} refuted`)

phase('Judge')
const SCORE_SCHEMA = { type: 'object', properties: { scores: { type: 'array', items: { type: 'object', properties: { name: { type: 'string' }, humid_evidence: { type: 'number' }, absolute_uptake: { type: 'number' }, mtv_headroom: { type: 'number' }, pipeline_fit: { type: 'number' }, synthesis: { type: 'number' }, novelty: { type: 'number' }, total: { type: 'number' }, note: { type: 'string' } }, required: ['name','total','note'] } }, top3: { type: 'array', items: { type: 'string' } }, rationale: { type: 'string' } }, required: ['scores','top3','rationale'] }
const LENSES = [
  'humid-performance-first: weight measured humid retention and absolute CO2 at 0.15 bar most; be sceptical of breakthrough-only data',
  'design-headroom-first: weight how much a multivariate linker-substitution study could add (positions, known linker libraries, mixed-linker precedents) and novelty vs literature',
  'feasibility-first: weight synthesis/scale-up reality, CIF availability, and whether our rigid GCMC pipeline can produce a defensible number within ~2 weeks of compute on 24 cores',
]
const judged = (await parallel(LENSES.map((lens, i) => () => agent(`${CTX}\nSurvivors with verifier notes (JSON):\n${JSON.stringify(survivors.map(s => ({ c: s.c, evidence: s.evidence.corrected_facts, fit: s.fit.corrected_facts }))).slice(0, 50000)}\n\nRefuted (for context, do not score): ${killed.map(k => k.c.name).join(', ')}\n\nJudge lens ${i + 1}: ${lens}. Score each survivor 0-10 on humid_evidence, absolute_uptake, mtv_headroom, pipeline_fit, synthesis, novelty; total per your lens weighting; name top3 with rationale. Be concrete: cite the numbers you weigh.\n${OUT}`, { label: `judge:${i + 1}`, phase: 'Judge', schema: SCORE_SCHEMA, model: 'opus' })))).filter(Boolean)
const critic = await agent(`${CTX}\nRoster: ${roster.map(r => r.name).join(', ')}\nSurvivors: ${survivors.map(s => s.c.name).join(', ')}\nRefuted: ${killed.map(k => `${k.c.name} (${k.evidence && k.evidence.refuted ? 'evidence' : ''}${k.fit && k.fit.refuted ? ' fit' : ''})`).join('; ')}\nDropped at merge: ${(merged ? merged.dropped : []).join('; ')}\nNot-found lists from sweeps: ${ext.flatMap(r => r.not_found || []).join('; ')}\n\nCompleteness critic: what is MISSING? Families or specific frameworks not searched, claims not verified, a modality not run (e.g. patents, Korean/Chinese literature, 2025-2026 preprints, CSD/CoRE database queries by PLD window 3.3-4.5 A + azolate), and any refutation that looks wrong (over-eager). Return a prioritized list of gaps with a one-line search recipe each, and any candidates you believe were wrongly refuted with why.`, { label: 'critic', phase: 'Judge', model: 'opus' })

return { repoDigest: repoDigest.slice(0, 20000), rosterCount: roster.length, roster, dropped: merged ? merged.dropped : [], verified, survivors: survivors.map(s => s.c.name), judged, critic, notFound: ext.flatMap(r => r.not_found || []) }