export const meta = {
  name: 'magi003-verify-r1-claims',
  description: 'Adversarially verify the factual and effectiveness claims in two sealed MAGI-003 R1 positions (laptop, laptop2) plus cross-position conflicts',
  phases: [
    { title: 'Verify', detail: 'evidence + effectiveness refuters per claim' },
    { title: 'Cross', detail: 'conflicts between the two positions' },
  ],
}

const CTX = `Context: MOF simulation project for CO2 capture from wet flue gas. Registered ruler: CO2 0.15 bar, 298 K, RH 90 %, TSA 298->373 K humid working capacity + retention (RH90/RH0) + absolute uptake at 0.15 bar. Pipeline: RASPA rigid-framework GCMC (UFF_MOF, Garcia-Sanchez CO2, TIP5P-Ew water), PACMAN DDEC6 charges, xtb GFN-FF relaxation (only on desktop), Zeo++ gates (PLD > 3.3 A required for CO2; LCD drop < 20 %). Physisorption only: chemisorption, open-metal-site water coordination, flexible gating cannot be modelled. Reference numbers from our ZIF-69 work: base RH0 CO2 0.5839 mol/kg, saIm050 retention 92.0 % (n=1) / 83.5 % (n=5 mean), saIm100 54.7 %, sa50nb50 82.4 %; batch (arrangement) unit 8.7 percentage points. Compute: RH90 one composition ~6 h/chain chunk on laptop2, ~4.5 h on desktop; ensembles of 5 realizations are the standard.`

const CLAIMS = [
  { who: 'Melchior', id: 'M-A1', claim: 'MUF-16 [M(Haip)2] (M = Ni, Co, Mn) is isostructural for the three metals, space group I2/a, has 1D channels, NO open metal sites (metal saturated by 4 carboxylate O + 2 amino N), linker 5-aminoisophthalic acid (cheap, commercial), gram-scale high-yield synthesis. Source DOI 10.1038/s41467-020-20489-2 (Qazvini et al. Nat Commun 2021).' },
  { who: 'Melchior', id: 'M-A2', claim: 'MUF-16 has NO published humid CO2 data; the paper only states it withstands oxygen and water vapour. PLD/LCD and CO2 uptake at 0.15 bar / 298 K are unverified. (Check: does the paper or later literature report CO2 uptake at 0.15 bar, water isotherms, humid breakthrough, PLD/LCD?)' },
  { who: 'Melchior', id: 'M-A3', claim: 'MUF-16 amine groups act by physisorption (not carbamate chemisorption), so rigid GCMC with UFF_MOF + DDEC6 applies; and the linker offers substitution headroom (amino + ring positions) so a multivariate substitution study is possible without changing topology.' },
  { who: 'Melchior', id: 'M-B1', claim: 'IISERP-MOF2 (Kwon et al. ACS Cent. Sci. 2025, DOI 10.1021/acscentsci.5c00777, ref 31 there) has the lowest process energy in that screening because its N2 adsorption is unusually low; PLD in the 2.6-3.7 A group; humid experiments were reported. Framework code, topology, metal, linker, RH, equilibrium-vs-breakthrough, numbers all unverified. (Find the primary paper, CSD refcode, composition, PLD, CO2 at 0.15 bar, humid data.)' },
  { who: 'Melchior', id: 'M-C1', claim: 'CALF-20 PLD is 2.75 A per Kwon 2025 main text, which is below the CO2 kinetic diameter 3.3 A, so rigid GCMC would give ~0 CO2 uptake; if it adsorbs in reality it must be flexible; so CALF-20 is a negative control for our pipeline. (Check: what do Lin et al. Science 2021 and other GCMC studies of CALF-20 actually obtain with rigid frameworks? Is PLD 2.75 the Zeo++ value or another definition?)' },
  { who: 'Balthasar', id: 'B-A1', claim: 'CALF-20 / SquCALF-20 / Zn2(Atz)2(ox): topology dmc, Zn(II), 1,2,4-triazolate or 3-amino-1,2,4-triazolate + oxalate or squarate pillar, PLD ~3 A, LCD ~4.3 A, BET 550 m2/g; CO2 at 0.15 bar 298 K: parent 2.6 mmol/g, SquCALF-20 3.6 mmol/g (1.38x); CO2/N2 selectivity 500 (dry); at 0.15 bar the same paper measured 273 K 3.3, 323 K 1.9, 343 K 1.3 mmol/g. Sources: Nat Commun 2024 s41467-024-48136-0 (full text), Science 2021 abi7281, ACS Appl Eng Mater acsaenm.3c00622.' },
  { who: 'Balthasar', id: 'B-A2', claim: 'CALF-20 water isotherm is Type V with inflection below 20 % RH and saturation ~11 mmol/g; at 80 % RH water molecules have 1-2 hydrogen bonds each (bulk 3-4); parent CALF-20 keeps CO2 selectivity up to ~40 % RH and >1 mmol/g CO2 at 60 % RH; whether those humid numbers are equilibrium co-adsorption or breakthrough is unverified.' },
  { who: 'Balthasar', id: 'B-A3', claim: 'For CALF-20 the Nat Commun 2024 paper itself reports that rigid-framework GCMC UNDER-predicts CO2 (pore volume difference 11.9 % at 273 K) and that water changes the structure more than CO2 (triazole rotation 30-40 deg with water vs 20-30 deg with CO2); therefore RH90 is the condition where a rigid model breaks most. Also: an isoreticular substitution series (squarate for oxalate, amino-triazolate) is already reported, so a linker-substitution study can be mounted on CALF-20.' },
  { who: 'Balthasar', id: 'B-A4', claim: 'CALF-20 synthesis: industrial demonstration (Svante + BASF; Lafarge-Holcim ~1 t CO2/day), aqueous/methanol room-temperature ambient-pressure synthesis in ~6 min, linkers commercial and cheap.' },
  { who: 'Balthasar', id: 'B-B1', claim: 'Ni3(BTP)2 (Ni(II), 1,3,5-tris(1H-pyrazol-4-yl)benzene, Long group 2011) retains crystallinity 14 days in boiling water, pH 2 boiling acid and pH 14 boiling base; but there is NO humid CO2 adsorption data anywhere, PLD/LCD and CO2 at 0.15 bar unverified, H3BTP price unknown (typically expensive). (Check: is there any CO2/humid data; is there a CSD refcode; is BTP commercially available?)' },
  { who: 'Balthasar', id: 'B-C1', claim: 'TIFSIX-3-Ni (Ni(II)/pyrazine + TiF6 2-): structurally stable up to 80 % RH (SIFSIX-3-Ni undergoes a phase change at ~50 % RH); water uptake 7.5 mmol/g at 95 % RH; humid demonstrations are non-equilibrium cycling (breakthrough-type). NbOFFIVE-1-Ni: 5000 ppm CO2 dry 1.5 / humid 0.7 mmol/g, 10,000 ppm 1.8 / 1.1 mmol/g -> humid/dry ratios 0.47 and 0.61. Sources: Angew 2022 anie.202206613, Sci Adv 2019 sciadv.aax9171, PCCP 2024 26, 17645 (all abstracts only).' },
  { who: 'Balthasar', id: 'B-D1', claim: 'Cost claim: on laptop2 (6 cores) Zeo++ ~10 min/structure, Widom 37-57 min, dry GCMC 0.15 bar 1h38m-2h11m per job, RH90 binary GCMC ~6 h per composition (7 parallel); so 6 structures x 5 realizations = 30 jobs, ~30 h wall clock; the real unknown is whether xtb relaxation and PACMAN DDEC6 work on a non-ZIF framework (Zn-oxalate layers, fluorinated anion pillars) at all - zero prior runs. (Assess: is this cost realistic for CALF-20-size cells with 2x2x2 supercells and Ewald; does UFF_MOF cover Zn-oxalate and Ti/Nb-F; does PACMAN DDEC6 handle these elements; is GFN-FF reliable for these; what would break?)' },
]

const VERDICT = { type: 'object', properties: { verdict: { type: 'string', enum: ['확인', '정정', '반증', '미확인'] }, confidence: { type: 'number' }, findings: { type: 'string' }, corrected_numbers: { type: 'string' }, effectiveness_for_our_ruler: { type: 'string' }, sources_checked: { type: 'array', items: { type: 'string' } } }, required: ['verdict', 'confidence', 'findings', 'effectiveness_for_our_ruler', 'sources_checked'] }
const OUT = 'Return only the structured output. Every number needs a source (DOI/URL actually opened, or Semantic Scholar/Crossref metadata). Mark what you could not confirm as 미확인 rather than guessing. When a publisher blocks (403), use api.semanticscholar.org/graph/v1, Crossref, PMC, arXiv/ChemRxiv, or Google Scholar snippets.'

phase('Verify')
const results = await pipeline(CLAIMS,
  c => parallel([
    () => agent(`${CTX}\nClaim ${c.id} (${c.who}): ${c.claim}\n\nLens: EVIDENCE. Try to REFUTE or CORRECT the factual content: open the cited sources (or their metadata), check every number, the RH / pressure / temperature conditions, equilibrium vs breakthrough, the existence of the framework/CIF (CSD refcode, CoRE MOF entry), and the synthesis claims. State what is confirmed, what is wrong (with the right value), and what cannot be confirmed. Verdict rules: 확인 = central facts confirmed from a primary source; 정정 = confirmed with corrections; 반증 = central fact false; 미확인 = could not confirm.\n${OUT}`, { label: `evidence:${c.id}`, phase: 'Verify', schema: VERDICT, model: 'opus' }),
    () => agent(`${CTX}\nClaim ${c.id} (${c.who}): ${c.claim}\n\nLens: EFFECTIVENESS. Assume the facts are roughly as stated. Try to REFUTE that this gives anything on OUR ruler (RH90 humid TSA working capacity, retention, 0.15 bar absolute uptake) within our pipeline: (1) what would rigid GCMC with UFF_MOF/DDEC6/TIP5P-Ew predict for this material and why (compare to literature GCMC of the same material if any); (2) does RH 40-60 % literature data say anything about RH 90 % (water isotherm shape, pore filling, competitive vs cooperative); (3) is the proposed substitution/multivariate headroom real for this framework (which positions, which reported analogues, does it keep topology); (4) is the 2-week cost claim realistic given cell size, Ewald, 2x2x2 supercell, ensembles of 5; (5) what would the result actually let the project say on a poster that it cannot already say with ZIF-69? Verdict rules as: 확인 = effective on our ruler with a concrete path; 정정 = effective only under stated corrections; 반증 = would not yield a usable number/claim; 미확인.\n${OUT}`, { label: `effect:${c.id}`, phase: 'Verify', schema: VERDICT, model: 'opus' }),
  ]).then(v => ({ id: c.id, who: c.who, claim: c.claim, evidence: v[0], effectiveness: v[1] }))
)
log(`verified ${results.filter(Boolean).length}/${CLAIMS.length} claims`)

phase('Cross')
const cross = await agent(`${CTX}\nTwo sealed positions (summaries):\nMELCHIOR (laptop, EndNote-library source): top3 = MUF-16 (Ni/Co/Mn) [no humid data, physisorbing amine, substitution headroom], IISERP-MOF2 [Kwon 2025 lowest process energy via low N2; details unverified], CALF-20 [as negative control: PLD 2.75 A < 3.3 A so rigid GCMC gives 0]. Key stance: no candidate has data on our ruler (literature humid = RH 40 % GCMC or unknown), so no ranking; n=1 per framework cannot separate anything (batch unit 8.7 p).\nBALTHASAR (laptop2, web, no subagents): top3 = CALF-20 isoreticular family (SquCALF-20, Zn2(Atz)2(ox)) [PLD ~3 A, LCD ~4.3, 0.15 bar 2.6/3.6 mmol/g, Type-V water, rigid GCMC under-predicts, industrial], Ni3(BTP)2 [stability only], TIFSIX-3-Ni [humid/dry ratios from NbOFFIVE-1-Ni 0.47/0.61 at ppm-level CO2]. Key stance: move the existing 'fixed topology + linker substitution + batch statistics' machine onto a proven framework; risk is front-end (relax/charges on non-ZIF), not compute.\n\nVerification results so far (JSON): ${JSON.stringify(results.filter(Boolean).map(r => ({ id: r.id, ev: r.evidence && r.evidence.verdict, evf: r.evidence && r.evidence.findings, eff: r.effectiveness && r.effectiveness.verdict, efff: r.effectiveness && r.effectiveness.effectiveness_for_our_ruler }))).slice(0, 40000)}\n\nTask: list every CONFLICT between the two positions (same material, different numbers or different conclusions - e.g. CALF-20 PLD 2.75 vs ~3 A and 'rigid gives 0' vs 'rigid under-predicts by ~12 %'; MUF-16 'no humid data' vs anything the other side or literature says; whether RH 40 % data can be extrapolated), and for each conflict say which side the evidence supports and what one-line attack each side deserves. Then list the three strongest attacks on EACH position overall (numbers-first), and one attack that applies to BOTH (e.g. n=1 cannot separate; no candidate on the registered ruler; front-end unproven). Return prose in Korean, concise, sourced.`, { label: 'cross-conflicts', phase: 'Cross', model: 'opus' })

return { results, cross }