export const meta = {
  name: 'magi003-supplement-verify',
  description: 'Verify 7 supplement candidates the truncated merge missed (Ni-4-PyC/IISERP-MOF2, Ni-TM-DMOF, ZnF(daTz), SBMOF-1, HAWZEM, UTSA-280, MCIF-1)',
  phases: [ { title: 'Supplement' } ],
}
const CTX = "Context: MOF simulation project for CO2 capture from wet flue gas. Registered ruler: CO2 0.15 bar, 298 K, RH 90 %, TSA 298->373 K humid working capacity + retention (RH90/RH0) + absolute uptake at 0.15 bar. Pipeline: RASPA rigid-framework GCMC (UFF_MOF, Garcia-Sanchez CO2, TIP5P-Ew water), PACMAN DDEC6 charges, xtb GFN-FF relaxation, Zeo++ gates (PLD > 3.3 A). Physisorption only: chemisorption, open-metal-site water coordination, flexible gating cannot be modelled. Method = fixed topology + linker substitution ladders + ensembles of 5 realizations + batch statistics. Reference: ZIF-69 base RH0 CO2 0.5839 mol/kg, saIm050 retention 92.0 % (n=1)/83.5 % (n=5). 2-week compute window on 24 cores."
const OUT = "Return only the structured output. Every number needs a source actually opened (DOI/URL) or Semantic Scholar/Crossref/PMC/DataCite metadata. Mark unconfirmed as 미확인. findings <= 350 words. When a publisher blocks (403) use api.semanticscholar.org/graph/v1, Crossref, PMC, arXiv/ChemRxiv, OSTI."
const ITEMS = [
  { name: 'Ni-4-PyC = IISERP-MOF2 (Ni isonicotinate)', claim: 'Sweep record: JACS 2016 10.1021/jacs.6b10455 — parasitic energy 655 kJ/kg CO2 (lowest reported), humid breakthrough loses only 7 % of max CO2 capacity, CO2 isotherm unchanged after 7 days at >85 % RH and 6 months air; two pore sizes 3.5/4.8 A (Sci Adv 2015 10.1126/sciadv.1500421); 0.15 bar value unknown; rigid, Ni fully coordinated?; substituted isonicotinates (2-amino, 3-hydroxy, 2-chloro, 3-nitro) commercial. Check: the humid numbers and RH/conditions (equilibrium vs breakthrough), the 0.15 bar/298 K uptake, CSD refcode/CIF, OMS status, whether substituted-isonicotinate analogues keep the net.' },
  { name: 'Ni-TM-DMOF (Ni(TM-BDC)(dabco)0.5)', claim: 'Sweep record: negligible CO2 performance loss under 80 % RH breakthrough (10.1016/j.micromeso.2025.113559 via 10.1039/d6sc03678c), 5.0 mmol/g at 273 K/1 bar; metal (Zn->Ni) x methylation degree (BDC/2-Me/2,5-Me2/TM-BDC) grid already synthesized; DMOF flexibility risk. Check the primary paper: RH, dry vs humid capacities, 0.15 bar/298 K, water isotherm, flexibility/breathing evidence, CIF availability, whether a rigid GCMC would be meaningful.' },
  { name: 'ZnF(daTz) amino-triazolate MAF (JACS 2020 10.1021/jacs.9b12879)', claim: 'Sweep record: CO2/N2 selectivity up to 120, CO2/H2O kinetic selectivity 70, CO2 at channel centre and H2O at corners (spatially separated sites), pre-adsorbed water raises Qst(CO2) 25-30 %; Zn2(daTz)2SO4 MTV series (10.1002/anie.202512425). Check: absolute CO2 at 0.15 bar, RH of humid tests, equilibrium co-adsorption data, PLD/LCD, CIF, flexibility, and whether the site segregation is a checkable equilibrium prediction for rigid GCMC density grids.' },
  { name: 'SBMOF-1 / Ca(SDB) (CSD ZERQOE)', claim: 'Sweep record: ranked #1 for CO2/H2O selectivity (80) in a ternary GCMC CoRE-MOF screen at RH 80 % (Langmuir 2016 10.1021/acs.langmuir.6b02803), LCD 4.5 A, VF 0.25, sulfone acceptor site; synthesized (Banerjee/Parise 2012 10.1021/cg300274n). Check: any EXPERIMENTAL humid CO2 or water isotherm for SBMOF-1; 0.15 bar CO2; CIF; UFF/UFF4MOF coverage for Ca; sulfone-bridge substitution analogues (oxydibenzoate, thiodibenzoate) reported?' },
  { name: 'HAWZEM (Cu isonicotinate, bcu)', claim: 'Sweep record: #3 in the same Langmuir 2016 ternary screen, adsorbs no water across 0.1-1 bar at RH 80 %, LCD 4.8 A; synthesized (Lian & Chen 2012 Inorg Chem Commun 18, 8). Check: open axial Cu(II) site in the CIF (OMS -> refute), any experimental CO2/humid data, 0.15 bar uptake, and relation to IISERP-MOF2.' },
  { name: 'UTSA-280 (Ca squarate)', claim: 'Sweep record: passes 100 % RH / 15 vol % CO2 cycling (Energy Fuels 2021 10.1021/acs.energyfuels.1c01642), 1D channels 3.2 x 4.5 A, coordinated water part of framework, rigid GCMC by Sholl group in RASPA (Chem Mater 2023 10.1021/acs.chemmater.3c00065), collapse at 150 C; no ring positions for substitution (metal/ring-size axes only). Check: humid retention % and conditions, 0.15 bar/298 K CO2, whether the 1D isolated channels make equilibrium GCMC over-predict, CIF with coordinated water.' },
  { name: 'MCIF-1 (Cu(I) 4,5-dicyanoimidazolate, CSD JAWXEN)', claim: 'Sweep record: room-temperature scalable synthesis, water/pH 0-13.5 stable (Faraday Discuss 2017 10.1039/c7fd00017k), nominated by Kwon 2025 (10.1021/acscentsci.5c00777) as a 1D-channel motif surviving the 40 % RH multicomponent GCMC filter; no experimental CO2 data; imidazolate 4,5-positions give a CN/NO2/Cl/H MTV ladder. Check: any CO2 isotherm at all, PLD/LCD, CIF desolvated phase, Cu(I) oxidation risk, what Kwon actually reports for it (numbers).' },
]
const VERDICT = { type: 'object', properties: { verdict: { type: 'string', enum: ['확인','정정','반증','미확인'] }, confidence: { type: 'number' }, findings: { type: 'string' }, corrected_numbers: { type: 'string' }, effectiveness_for_our_ruler: { type: 'string' }, cif_and_positions: { type: 'string' }, sources_checked: { type: 'array', items: { type: 'string' } } }, required: ['verdict','confidence','findings','effectiveness_for_our_ruler','sources_checked'] }
phase('Supplement')
const out = await pipeline(ITEMS, c => agent(`${CTX}\nCandidate: ${c.name}\n${c.claim}\n\nOne combined adversarial pass: (A) EVIDENCE - confirm/correct numbers and conditions from primary sources; (B) FIT - modelability with rigid GCMC (OMS, flexibility, chemisorption -> refute), CIF availability, real substitution headroom for a fixed-topology ladder, whether 0.15 bar / RH90 / TSA is meaningful, realistic 2-week cost. Verdict: 확인 = worth our compute with a concrete path; 정정 = worth it under corrections; 반증 = not worth it; 미확인.\n${OUT}`, { label: `sup:${c.name.slice(0,36)}`, phase: 'Supplement', schema: VERDICT, model: 'opus', effort: 'medium' }).then(v => ({ name: c.name, v })))
return out